language: php
php:
  - 5.5
  - 5.4
  - 5.3

env:
  - JVERSION_TEST=3.3

branches:
  only:
    - development

install:
  - composer selfupdate
  - composer update

before_script:
  - mysql -e 'create database fof_test;'
  - if [[ "$JVERSION_TEST" == "3.3" ]]; then cp tests/environments/3.3/joomla.sql joomla.sql; fi
  - mysql fof_test < joomla.sql
  - cp build/templates/include.php fof/include.php

after_script:
  - cat Tests/debug.txt

notifications:
  email: false

script: php vendor/phpunit/phpunit/phpunit --bootstrap=Tests/bootstrap.php Tests
